apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodered-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodered
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodered
  template:
    metadata:
      labels:
        app: nodered
    spec:
      containers:
      - name: nodered
        image: tsilian9/cloudfield-nodered:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 1880
        env:
        - name: RABBIT_HOST
          valueFrom:
            configMapKeyRef:
              name: farm-settings
              key: RABBITMQ_HOST
        - name: RABBIT_PORT
          valueFrom:
            configMapKeyRef:
              name: farm-settings
              key: RABBITMQ_PORT
        - name: RABBIT_USER
          valueFrom:
            secretKeyRef:
              name: farm-secrets
              key: RABBITMQ_USER
        - name: RABBIT_PASS
          valueFrom:
            secretKeyRef:
              name: farm-secrets
              key: RABBITMQ_PASS
        volumeMounts:
        - mountPath: /data
          name: nodered-data
      volumes:
      - name: nodered-data
        persistentVolumeClaim:
          claimName: nodered-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nodered
spec:
  selector:
    app: nodered
  ports:
    - name: nodered
      port: 1880
      targetPort: 1880
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodered-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: nodered.172.31.76.79.nip.io  
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nodered
            port: 
              number: 1880
